### ISSUE TITLE
Vulkan Queue is nullptr!

### ISSUE THREAD

**Issue by Kliaxe** [enjiushi/VulkanLearn#2]
Hi again! After my previous issue, which wasn't that big of a deal, i tried to continue to build the solution. This time, a very strange thing happened. I'm getting a read access violation, saying "initial_state_layout" was nullptr. As you can see here in this real-time debugging environment:

![image](https://user-images.githubusercontent.com/16865975/63048902-c7bfe980-bed7-11e9-9973-58571d9ae049.png)

This is the output i was getting:
`Exception thrown: read access violation.
**initial_layout_state** was nullptr.`

It seems to be the only problem, preventing me from running the application. 

@enjiushi If you have any thoughts on this I'd gladly hear them. It's so strange how it runs so well on your pc, while I for instance am struggling.
For future visitors, it would be nice to have a "Build" section in your README.md.

Would be amazing if you could share some hardware information, such as gpu, drivers, VS version and even OS, which the build was tested on.

And again, your project as a whole is learnful and easy to read/follow. I have learned so much from your project and about Vulkan. Thank you 👍

**Comment by Kliaxe** [comment]
![image](https://user-images.githubusercontent.com/16865975/63053911-276fc200-bee3-11e9-9f37-5a264ec895e5.png)

Just a quick update. This is the call stack of the current situation. Thought it might be helpfull

**Comment by Kliaxe** [comment]
Update: The application is now running! Your last commit, successfully solved the issue. 

I'm now closing the issue...

**Comment by enjiushi** [comment]
Hi buddy

Sorry I wasn't noticed that you send me an email:)

Yep it was recently upgraded to latest vulkan, and a lot of validation
errors pops up. I've fixed them.

This project only works on my pc. I haven't tried somewhere else. So if you
met any problem, feel free to let me know, I'll try to fix

Kliaxe <notifications@github.com> 于2019年8月15日周四 上午3:41写道：

**Comment by enjiushi** [comment]
Since there's no visitors using this project, I didn't really keep every commit 100% correct. Shit could happen :)

I'm gonna complete the doc and add a section about how to build. It's amazing that you could run it without any of it. I wonder if it runs okay and smooth on your pc? As I'm troubling with the unstable frame interval. I want to spend sometime to investigate

**Comment by Kliaxe** [comment]
Hi again

Sorry for the long response. So I've tried to use the HDR texture and i gotta say, the demo is absolutely stunning! I didn't get any errors of some kind, even from Vulkan. Everything just chains extremely well together!

The only thing that stood out to me was the checkered patterns, when the animated model moved:

![image](https://user-images.githubusercontent.com/16865975/63599030-05e89780-c5c1-11e9-8646-83c9b794d090.png)

Is this the unstable frame interval you were talking about?

I'm using a graphics card from Nvidia, and Windows 10 1903, in case you are curious :)

**Comment by enjiushi** [comment]
Hi Kliaxe

I think that's the issue comes from temporal resolve. Sophia(the girl in the middle) also has ghosting effect when she moves her arm. I'm gonna check into this.

The unstable frame interval I meant was about some feeling like frame juddering, which sometimes makes you feel like one frame is skipped. This is very obvious when you run in debug mode. Release mode on the other hand is smooth(frame rate is a lot more stable).

Feel free to log issues, I'll fix them:)
